name: Build

on:
  workflow_dispatch
  # schedule:
  #  - cron: '5 5 * * *'

# permissions:
#   contents: write

env:
  MICROPYTHON_REPO_SHORT: micropython/micropython
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0

defaults:
  run:
    shell: bash

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      MICROPYTHON_PREBUILT_LATEST_TAG: ${{ steps.release_latest_tag.outputs.MICROPYTHON_PREBUILT_LATEST_TAG }}
      MICROPYTHON_LATEST_RELEASE: ${{ steps.release_commit_id.outputs.MICROPYTHON_LATEST_RELEASE }}
    
    steps:
      - name: Get latest release tag of this repo
        id: release_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          cd /tmp/
          MICROPYTHON_PREBUILT_LATEST_TAG=$(gh release list -R $OWNER/$REPO --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "MICROPYTHON_PREBUILT_LATEST_TAG=$MICROPYTHON_PREBUILT_LATEST_TAG" >> $GITHUB_OUTPUT
          echo "MICROPYTHON_PREBUILT_LATEST_TAG=$MICROPYTHON_PREBUILT_LATEST_TAG" >> $GITHUB_ENV

      - name: Clone repo and check if there is a new and uncompiled yet version
        id: release_commit_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/

          MICROPYTHON_LATEST_RELEASE=$(gh release list -R $MICROPYTHON_REPO_SHORT --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "$MICROPYTHON_LATEST_RELEASE"
          echo "MICROPYTHON_LATEST_RELEASE=$MICROPYTHON_LATEST_RELEASE" >> $GITHUB_ENV
          echo "MICROPYTHON_LATEST_RELEASE=$MICROPYTHON_LATEST_RELEASE" >> $GITHUB_OUTPUT

          # case: no new commit => abort the workflow
          if [[ $MICROPYTHON_PREBUILT_LATEST_TAG == $MICROPYTHON_LATEST_RELEASE ]]; then
            echo "[!] No new version to compile"
            exit 100
          fi

  
  build:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: s132_nrf52_6_1_1
            OS: ubuntu-latest
            
          - TARGET: s140_nrf52_6_1_1
            OS: ubuntu-latest
            
          - TARGET: s140_nrf52_7_3_0
            OS: ubuntu-latest

            
    runs-on: ${{ matrix.OS }}

    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}

      MICROPYTHON_PREBUILT_LATEST_TAG: ${{ needs.checkout.outputs.MICROPYTHON_PREBUILT_LATEST_TAG }}
      MICROPYTHON_LATEST_RELEASE: ${{ needs.checkout.outputs.MICROPYTHON_LATEST_RELEASE }}
      
    steps:
      - uses: actions/checkout@v7
      
      - name: Download MicroPython
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/
          MICROPYTHON_VERSION_SHORT="${MICROPYTHON_LATEST_RELEASE#v}"
          
          gh release download "$MICROPYTHON_LATEST_RELEASE" --repo "$MICROPYTHON_REPO_SHORT" --pattern "micropython-*.tar.xz"
          tar -xJf "micropython-$MICROPYTHON_VERSION_SHORT.tar.xz"
          MICROPYTHON_ROOT_DIR="/tmp/micropython-$MICROPYTHON_VERSION_SHORT"
          echo "MICROPYTHON_ROOT_DIR=$MICROPYTHON_ROOT_DIR" >> $GITHUB_ENV

      
      - name: Install dependencies and set env vars
        run: | 
          cd /tmp/
          $APT update
          $APT install binutils-arm-none-eabi build-essential gcc-arm-none-eabi libffi-dev libnewlib-arm-none-eabi pkg-config python3 unzip

          cd "$MICROPYTHON_ROOT_DIR/ports/nrf/drivers/bluetooth/"
          chmod o+x "./download_ble_stack.sh"
          "./download_ble_stack.sh" "$TARGET"

          IFS=_ read -r SD FAMILY MAJOR MINOR PATCH <<< "$TARGET"
          SOFTDEV_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $SD
          echo $SOFTDEV_VERSION
          
          echo "SD=$SD" >> $GITHUB_ENV
          echo "SOFTDEV_VERSION=$SOFTDEV_VERSION" >> $GITHUB_ENV

        
      - name: Run build
        run: |
          cd "$MICROPYTHON_ROOT_DIR/ports/nrf/"
          #make submodules
          make BOARD=SUPERMINI_NRF52840 BOARD_DIR="$GITHUB_WORKSPACE/ProMicro_config_files" SD="$SD" SOFTDEV_VERSION="$SOFTDEV_VERSION"
          ls -alh

          exit 1

                
      - name: List build information
        run: |
          OLD_MICROPYTHON_BIN_DIR="$MICROPYTHON_ROOT_DIR/target/$TARGET/release"
          OLD_MICROPYTHON_BIN_PATH="$OLD_MICROPYTHON_BIN_DIR/$MICROPYTHON_BIN_NAME"
          ls -alh "$OLD_MICROPYTHON_BIN_DIR"
          if [[ $TARGET == *-windows-* ]]; then
            OLD_MICROPYTHON_BIN_PATH="$OLD_MICROPYTHON_BIN_DIR/$MICROPYTHON_BIN_NAME.exe"
          fi
          
          MICROPYTHON_BIN_PATH="${{ runner.temp }}/$MICROPYTHON_BIN_NAME-$MICROPYTHON_VERSION-$TARGET"
          if [[ $OS == windows* || $TARGET == *-windows-* ]]; then
            MICROPYTHON_BIN_PATH="${{ runner.temp }}/$MICROPYTHON_BIN_NAME-$MICROPYTHON_VERSION-$TARGET.exe"
          fi
          MICROPYTHON_BIN_HASH_PATH="$MICROPYTHON_BIN_PATH.sha256.txt"
          
          cp -f "$OLD_MICROPYTHON_BIN_PATH" "$MICROPYTHON_BIN_PATH"
          ls -alh "$MICROPYTHON_BIN_PATH"

          cd "$(dirname "$MICROPYTHON_BIN_PATH")"
          sha256sum --tag "$(basename "$MICROPYTHON_BIN_PATH")" | tee "$MICROPYTHON_BIN_HASH_PATH"
          ldd "$MICROPYTHON_BIN_PATH" || true
          "$MICROPYTHON_BIN_PATH" -h || true 
          
          echo "MICROPYTHON_BIN_PATH=$MICROPYTHON_BIN_PATH" >> $GITHUB_ENV
          echo "MICROPYTHON_BIN_HASH_PATH=$MICROPYTHON_BIN_HASH_PATH" >> $GITHUB_ENV
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.TARGET }}
          path: |
            ${{ env.MICROPYTHON_BIN_PATH }}
            ${{ env.MICROPYTHON_BIN_HASH_PATH }}


  deploy_release:
    needs: [checkout, build]
    runs-on: ubuntu-latest
    env:
       MICROPYTHON_CURRENT_COMMIT_ID: ${{ needs.checkout.outputs.MICROPYTHON_CURRENT_COMMIT_ID }}
       MICROPYTHON_VERSION: ${{ needs.checkout.outputs.MICROPYTHON_VERSION }}
    
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v8
       with:
        pattern: binary-*
        merge-multiple: true
        path: /tmp/results

     - name: List target
       run: |
          cd "/tmp/results"
          ls -alh
  
          RELEASE_NOTES="/tmp/release_notes.txt"
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          
          cat *.sha256.txt > "$RELEASE_NOTES"
          sha256sum -c *.sha256.txt
          
          mkdir -p "/tmp/hashes"
          mv -f *.sha256.txt "/tmp/hashes/"
  
     - name: Create a new Github release
       uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b #v3.0.1
       with:
         make_latest: true
         body_path: ${{ env.RELEASE_NOTES }}
         name: version ${{ env.MICROPYTHON_VERSION }} - build ${{ env.MICROPYTHON_CURRENT_COMMIT_ID }}
         tag_name: ${{ env.MICROPYTHON_CURRENT_COMMIT_ID }}
         files: |
           /tmp/results/${{ env.MICROPYTHON_BIN_NAME }}-*
