name: Build

on:
  workflow_dispatch
  # schedule:
  #  - cron: '5 5 * * *'

permissions:
  contents: write

env:
  MICROPYTHON_REPO_SHORT: micropython/micropython
  MICROPYTHON_NRF_REL_PATH: ports/nrf/
  MICROPYTHON_NRF_BLUETOOTH_REL_PATH: ports/nrf/drivers/bluetooth/
  BOARD_NAME: PROMICRO_NRF52840
  
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0

defaults:
  run:
    shell: bash

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      MICROPYTHON_PREBUILT_LATEST_TAG: ${{ steps.release_latest_tag.outputs.MICROPYTHON_PREBUILT_LATEST_TAG }}
      MICROPYTHON_LATEST_RELEASE: ${{ steps.release_commit_id.outputs.MICROPYTHON_LATEST_RELEASE }}
    
    steps:
      - name: Get latest release tag of this repo
        id: release_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          cd /tmp/
          MICROPYTHON_PREBUILT_LATEST_TAG=$(gh release list -R $OWNER/$REPO --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "MICROPYTHON_PREBUILT_LATEST_TAG=$MICROPYTHON_PREBUILT_LATEST_TAG" >> $GITHUB_OUTPUT
          echo "MICROPYTHON_PREBUILT_LATEST_TAG=$MICROPYTHON_PREBUILT_LATEST_TAG" >> $GITHUB_ENV

      - name: Clone repo and check if there is a new and uncompiled yet version
        id: release_commit_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/

          MICROPYTHON_LATEST_RELEASE=$(gh release list -R $MICROPYTHON_REPO_SHORT --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "$MICROPYTHON_LATEST_RELEASE"
          echo "MICROPYTHON_LATEST_RELEASE=$MICROPYTHON_LATEST_RELEASE" >> $GITHUB_ENV
          echo "MICROPYTHON_LATEST_RELEASE=$MICROPYTHON_LATEST_RELEASE" >> $GITHUB_OUTPUT

          # case: no new commit => abort the workflow
          if [[ $MICROPYTHON_PREBUILT_LATEST_TAG == $MICROPYTHON_LATEST_RELEASE ]]; then
            echo "[!] No new version to compile"
            exit 100
          fi

  
  build:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: s132_nrf52_6_1_1
            OS: ubuntu-latest
            
          - TARGET: s140_nrf52_6_1_1
            OS: ubuntu-latest
            
          - TARGET: s140_nrf52_7_3_0
            OS: ubuntu-latest

            
    runs-on: ${{ matrix.OS }}

    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}

      MICROPYTHON_PREBUILT_LATEST_TAG: ${{ needs.checkout.outputs.MICROPYTHON_PREBUILT_LATEST_TAG }}
      MICROPYTHON_LATEST_RELEASE: ${{ needs.checkout.outputs.MICROPYTHON_LATEST_RELEASE }}
      
    steps:
      - uses: actions/checkout@v7
      
      - name: Download MicroPython
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/
          MICROPYTHON_VERSION_SHORT="${MICROPYTHON_LATEST_RELEASE#v}"
          
          gh release download "$MICROPYTHON_LATEST_RELEASE" --repo "$MICROPYTHON_REPO_SHORT" --pattern "micropython-*.tar.xz"
          tar -xJf "micropython-$MICROPYTHON_VERSION_SHORT.tar.xz"
          MICROPYTHON_ROOT_DIR="/tmp/micropython-$MICROPYTHON_VERSION_SHORT"
          echo "MICROPYTHON_ROOT_DIR=$MICROPYTHON_ROOT_DIR" >> $GITHUB_ENV

      
      - name: Install dependencies and set env vars
        run: | 
          cd /tmp/
          $APT update
          $APT install binutils-arm-none-eabi build-essential gcc-arm-none-eabi libffi-dev libnewlib-arm-none-eabi pkg-config python3 unzip

          MICROPYTHON_NRF_PATH="$MICROPYTHON_ROOT_DIR/$MICROPYTHON_NRF_REL_PATH/"
          echo "MICROPYTHON_NRF_PATH=$MICROPYTHON_NRF_PATH" >> $GITHUB_ENV
          
          cd "$MICROPYTHON_ROOT_DIR/$MICROPYTHON_NRF_BLUETOOTH_REL_PATH/"
          chmod o+x "./download_ble_stack.sh"
          "./download_ble_stack.sh" "$TARGET"

          IFS=_ read -r SD FAMILY MAJOR MINOR PATCH <<< "$TARGET"
          SOFTDEV_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $SD
          echo $SOFTDEV_VERSION
          
          echo "SD=$SD" >> $GITHUB_ENV
          echo "SOFTDEV_VERSION=$SOFTDEV_VERSION" >> $GITHUB_ENV

        
      - name: Run build
        run: |
          if [[ "$TARGET" == "s132_nrf52_6_1_1" ]]; then
            sed -i '/MICROPY_HW_ENABLE_USB/d; $a#define MICROPY_HW_ENABLE_USB (0)' "$GITHUB_WORKSPACE/ProMicro_config_files/mpconfigboard.h"; 
          fi
          
          cd "$MICROPYTHON_NRF_PATH"
          make -j$(nproc) BOARD="$BOARD_NAME" BOARD_DIR="$GITHUB_WORKSPACE/ProMicro_config_files" SD="$SD" SOFTDEV_VERSION="$SOFTDEV_VERSION"
          
      - name: List build files
        run: |
          cd "$MICROPYTHON_NRF_PATH"
          ls -alh build-*
          file build-*/firmware*
                
      - name: Pack the build
        run: |
          RELEASE_FNAME="micropython-$MICROPYTHON_LATEST_RELEASE-$SD-$SOFTDEV_VERSION.zip"
          RELEASE_FNAME_HASH="$RELEASE_FNAME.sha256.txt"
          RELEASE_FNAME_PATH="$MICROPYTHON_ROOT_DIR/ports/nrf/$RELEASE_FNAME"
          RELEASE_FNAME_HASH_PATH="$MICROPYTHON_ROOT_DIR/ports/nrf/$RELEASE_FNAME_HASH"
          
          echo "RELEASE_FNAME=$RELEASE_FNAME" >> $GITHUB_ENV
          echo "RELEASE_FNAME_HASH=$RELEASE_FNAME_HASH" >> $GITHUB_ENV
          echo "RELEASE_FNAME_PATH=$RELEASE_FNAME_PATH" >> $GITHUB_ENV
          echo "RELEASE_FNAME_HASH_PATH=$RELEASE_FNAME_HASH_PATH" >> $GITHUB_ENV
          
          cd "$MICROPYTHON_ROOT_DIR/ports/nrf/"
          zip -r "$RELEASE_FNAME" build-$BOARD_NAME-$SD/firmware.*
          sha256sum --tag "$(basename "$RELEASE_FNAME")" | tee "$RELEASE_FNAME_HASH"

        
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.TARGET }}
          path: |
            ${{ env.RELEASE_FNAME_PATH }}
            ${{ env.RELEASE_FNAME_HASH_PATH }}


  deploy_release:
    needs: [checkout, build]
    runs-on: ubuntu-latest
    env:
       MICROPYTHON_LATEST_RELEASE: ${{ needs.checkout.outputs.MICROPYTHON_LATEST_RELEASE }}
    
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v8
       with:
        pattern: binary-*
        merge-multiple: true
        path: /tmp/results

     - name: List target
       run: |
          cd "/tmp/results"
          ls -alh
  
          RELEASE_NOTES="/tmp/release_notes.txt"
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          
          cat *.sha256.txt > "$RELEASE_NOTES"
          sha256sum -c *.sha256.txt
          
          mkdir -p "/tmp/hashes"
          mv -f *.sha256.txt "/tmp/hashes/"
  
     - name: Create a new Github release
       uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 #v3.0.2
       with:
         make_latest: true
         body_path: ${{ env.RELEASE_NOTES }}
         name: version ${{ env.MICROPYTHON_LATEST_RELEASE }}
         tag_name: ${{ env.MICROPYTHON_LATEST_RELEASE }}
         files: |
           /tmp/results/*.zip
